### ISSUE TITLE
Make `Recaptcha` component into a `use_recaptcha` hook

### ISSUE THREAD

**Issue by voidpumpkin** [security-union/yew-recaptcha#2]
[`Recaptcha` has no html in it](https://github.com/security-union/yew-recaptcha/blob/master/src/recaptcha/mod.rs#L46-L49), thus is has no reason to be a component.

You probably wanted it to be a component so you would be able to use hooks.
Luckily that's what custom hooks are for.

**Comment by darioalessandro** [comment]
Nice!!! Thank you for your feedback.

**Comment by griffobeid** [comment]
> Nice!!! Thank you for your feedback. 
> 
> 
> 
> I'll have to do some reading, @griffobeid what do you think? would you like to take on this?

@darioalessandro Heck yeah! I can pick this up

**Comment by darioalessandro** [comment]
This is done 👍 thank you @voidpumpkin
