### ISSUE TITLE
Missing link to github

### ISSUE THREAD

**Issue by voidpumpkin** [security-union/yew-recaptcha#3]
The crate manifest file (Cargo.toml) is probably missing a link to this repository as there is no link in crates.io
got:
![image](https://user-images.githubusercontent.com/32368314/197509755-e6b4e562-a190-4299-9b41-b340d160edb0.png)

expected something like:
![image](https://user-images.githubusercontent.com/32368314/197509814-4c68da03-a400-431d-8a04-b74deb8940a3.png)

**Comment by darioalessandro** [comment]
100% agree, I'm on it 😄

**Comment by darioalessandro** [comment]
Done 😄 

<img width="1728" alt="Screen Shot 2022-10-25 at 6 13 07 PM" src="https://user-images.githubusercontent.com/1176339/197899182-496fbfa5-c187-4859-8609-bf5a3528d7ec.png">
